In [ ]:
#資料檔路徑(資料檔：i_filepath，完成檔：o_filepath，內文說明檔：c_filepath)
filepath = '/content/MyGoogleDrive/My Drive/Colab Notebooks/Python-for-Titanic/Ch03/'
i_filepath = filepath 
o_filepath = filepath + '完成檔/'
c_filepath = filepath + '內文說明檔/'

#3-1 認識 pandas–從資料結構看起

# (圖)-試算表與pandas 資料框的對照

In [ ]:
from google.colab import drive
drive.mount('/content/MyGoogleDrive')
import pandas as pd
df = pd.read_excel(c_filepath + '學生成績檔.xlsx')
df.head()

Drive already mounted at /content/MyGoogleDrive; to attempt to forcibly remount, call drive.mount("/content/MyGoogleDrive", force_remount=True).

        ID name sex                  email  ...  第2次平時考  第3次平時考  第4次平時考  第5次平時考
0  1080001  丁軒軒   男  1080001@sun.tc.edu.tw  ...    88.0    82.0      87    92.0
1  1080002  王倫樺   女  1080002@sun.tc.edu.tw  ...   100.0    95.0      99    96.0
2  1080003  何宜敏   女  1080003@sun.tc.edu.tw  ...    87.0    86.0      82    82.0
3  1080004  何志陞   男  1080004@sun.tc.edu.tw  ...    92.0    99.0      91    92.0
4  1080005  吳ㄧ歌   女  1080005@sun.tc.edu.tw  ...     NaN    92.0      97    98.0

[5 rows x 9 columns]

# 3-1-1 建立與存取序列

#實作-利用Python一維串列存放資料【EX3-1.1a.ipynb】

# Step 01

In [ ]:
c = ['國文','英文','數學','資訊科技']
s = [84,92,88,95]

# Step 02

In [ ]:
print(c)
print(s)

['國文', '英文', '數學', '資訊科技']
[84, 92, 88, 95]

#實作-利用pandas套件建立序列【EX3-1.1b.ipynb】

# Step 01

In [ ]:
import pandas as pd

# Step 02

In [ ]:
c = ['國文','英文','數學','資訊科技']
s = [84,92,88,95]

# Step 03

In [ ]:
cs = pd.Series(c)
ss = pd.Series(s)
print(cs)
print(ss)

0      國文
1      英文
2      數學
3    資訊科技
dtype: object
0    84
1    92
2    88
3    95
dtype: int64

# Step 04

In [ ]:
print(cs[0])
print(ss[0])

國文
84

#實作-建立自定索引的序列【EX3-1.1c.ipynb】

# Step 01

In [ ]:
import pandas as pd
c = ['國文','英文','數學','資訊科技']
s = [84,92,88,95]

# Step 02

In [ ]:
sc = pd.Series(s, index=c)
print(sc)

國文      84
英文      92
數學      88
資訊科技    95
dtype: int64

# Step 03

In [ ]:
#使用內定索引
print(sc[1])
sc[1] = 100
print(sc[1])

#使用自定索引
print(sc['英文'])
sc['英文'] = 80
print(sc['英文'])

92
100
100
80

# 加廣知識：存取序列的多個元素

In [ ]:
#使用內定索引存取多個元素
ss = pd.Series([84,92,88,95])
print(ss[0:3])
print(ss[[1,3]])
nums=[1,3]
print(ss[nums])

0    84
1    92
2    88
dtype: int64
1    92
3    95
dtype: int64
1    92
3    95
dtype: int64

In [ ]:
#使用自定索引存取多個元素
sc = pd.Series([84,92,88,95], index=['國文','英文','數學','資訊科技'])
print(sc['國文':'數學'])
print(sc[['英文','資訊科技']])
nums=['英文','資訊科技']
print(sc[nums])

國文    84
英文    92
數學    88
dtype: int64
英文      92
資訊科技    95
dtype: int64
英文      92
資訊科技    95
dtype: int64

# 3-1-2 建立與存取資料框

#實作-利用Python list建立二維串列【EX3-1.2a.ipynb】

# Step 01

In [ ]:
sc = [['國文','英文','數學','資訊科技'],[84,92,88,95]]
print(sc)

[['國文', '英文', '數學', '資訊科技'], [84, 92, 88, 95]]

# Step 02

In [ ]:
print(len(sc))

2

# Step 03

In [ ]:
for i in range(len(sc[0])):
  print(sc[0][i],sc[1][i])

國文 84
英文 92
數學 88
資訊科技 95

#實作-呼叫pandas的DataFrame()函式建立資料框【EX3-1.2b.ipynb】

# Step 01

In [ ]:
import pandas as pd
c = ['國文','英文','數學','資訊科技']
s = [84,92,88,95]

# Step 02

In [ ]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

# Step 03

In [ ]:
df['科目'] = c
df['分數'] = s

# Step 04

In [ ]:
df

     科目  分數
0    國文  84
1    英文  92
2    數學  88
3  資訊科技  95

# Step 05

In [ ]:
for i in range(len(df)):
    print(df['科目'][i],df['分數'][i])

國文 84
英文 92
數學 88
資訊科技 95

#實作-自定資料框的列索引【EX3-1.2c.ipynb】

# Step 01

In [ ]:
import pandas as pd
c = ['國文','英文','數學','資訊科技']
s = [84,92,88,95]
df = pd.DataFrame()
df['科目'] = c
df['分數'] = s
df.index = ['第1科','第2科','第3科','第4科']
df

       科目  分數
第1科    國文  84
第2科    英文  92
第3科    數學  88
第4科  資訊科技  95

# Step 02

In [ ]:
for i in range(len(df)):
  print(df.index[i],df['科目'][i],df['分數'][i])

0 國文 84
1 英文 92
2 數學 88
3 資訊科技 95

#加廣知識：資料框參數設定

In [ ]:
import pandas as pd
n = ['丁軒軒','王倫華','何宜敏','陳志昇']
c = ['國文','英文','數學','社會','自然']
s = [[86,88,82,87,92],[92,100,95,99,96],[82,87,86,82,82],[91,92,99,91,92]]
df = pd.DataFrame(s, index=n, columns=c)
df

     國文   英文  數學  社會  自然
丁軒軒  86   88  82  87  92
王倫華  92  100  95  99  96
何宜敏  82   87  86  82  82
陳志昇  91   92  99  91  92

# 3-2 資料取得

#3-2-1 讀取資料檔

#實作-掛接Google雲端硬碟【EX3-2.1a.ipynb】

# Step 01

In [ ]:
from google.colab import drive
drive.mount('/content/MyGoogleDrive')

Drive already mounted at /content/MyGoogleDrive; to attempt to forcibly remount, call drive.mount("/content/MyGoogleDrive", force_remount=True).

#實作-pandas讀取CSV檔及印出資料【EX3-2.1b.ipynb】

# Step 01

In [ ]:
from google.colab import drive
drive.mount('/content/MyGoogleDrive')
import pandas as pd
df = pd.read_csv(i_filepath + 'Iris.csv')

Drive already mounted at /content/MyGoogleDrive; to attempt to forcibly remount, call drive.mount("/content/MyGoogleDrive", force_remount=True).

# Step 02

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

# 3-2-2 儲存(匯出)資料檔

#實作-將資料框儲存成CSV檔【EX3-2.2.ipynb】

# Step 01

In [ ]:
from google.colab import drive
drive.mount('/content/MyGoogleDrive')

Drive already mounted at /content/MyGoogleDrive; to attempt to forcibly remount, call drive.mount("/content/MyGoogleDrive", force_remount=True).

# Step 02

In [ ]:
import pandas as pd
n = ['丁軒軒','王倫樺','何宜敏','何志陞']
c = ['國文','英文','數學','社會','自然']
s = [[86,88,82,87,92],[92,100,95,99,96],[82,87,86,82,82],[91,92,99,91,92]]
df = pd.DataFrame(s, index=n, columns=c )
df

     國文   英文  數學  社會  自然
丁軒軒  86   88  82  87  92
王倫樺  92  100  95  99  96
何宜敏  82   87  86  82  82
何志陞  91   92  99  91  92

# Step 03

In [ ]:
filename='五科成績.csv'       
df.to_csv(o_filepath + filename)

# 3-2-3 由網址讀取資料檔

#實作-由網址讀取資料檔【EX3-2.3.ipynb】

# Step 01

In [ ]:
import pandas as pd
df=pd.read_csv('https://data.epa.gov.tw/api/v1/aqx_p_322?limit=1000&api_key=9be7b239-557b-4c10-9775-78cadfc555e9&format=csv')
df.head()

   SiteId SiteName County  ...  ItemUnit          MonitorDate Concentration
0       1       基隆    基隆市  ...     μg/m3  2021-05-06 00:00:00            18
1       2       汐止    新北市  ...     μg/m3  2021-05-06 00:00:00            25
2       3       萬里    新北市  ...     μg/m3  2021-05-06 00:00:00            19
3       4       新店    新北市  ...     μg/m3  2021-05-06 00:00:00            19
4       5       土城    新北市  ...     μg/m3  2021-05-06 00:00:00            21

[5 rows x 9 columns]

# Step 02

In [ ]:
filename='PM25.csv'       
df.to_csv(o_filepath + filename)

# 3-2-4 網路爬蟲

#實作-網路爬蟲-台灣彩券【EX3-2.4.ipynb】

# Step 01-02

In [ ]:
import pandas as pd
url='https://www.taiwanlottery.com.tw/Lotto/Lotto649/history.aspx'
df = pd.read_html(url)
df

[                                                   0
 0  .style3 {color: #FF0000} .style5 {color: #FF00...,
                                                    0
 0  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000045  110/05/...
 1  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000044  110/04/...
 2  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000043  110/04/...
 3  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000042  110/04/...
 4  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000041  110/04/...
 5  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000040  110/04/...
 6  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000039  110/04/...
 7  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000038  110/04/...
 8  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000037  110/04/...
 9  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000036  110/04/...,
             0          1          2  ...          7          8          9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額       獎金總額
 1   110000045  110/05/04  110/05/04  ...  121406835  121406835  121406835
 2          獎號         獎號         獎號  ...         獎號        特別號        特別號
 3        開出順序       開出順序         27  ...         05         42         42
 4        大小順序       大小順序         05  ...         37         42         42
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配       獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎         普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號        任3個
 8      中獎  注數          0          0  ...       2100      20583      34215
 9      單注  獎金          0          0  ...       1000        400        400
 10   累至次  期獎金   85311966   85311966  ...        NaN        NaN        NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8         9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額      獎金總額
 1   110000044  110/04/30  110/04/30  ...   95276229   95276229  95276229
 2          獎號         獎號         獎號  ...         獎號        特別號       特別號
 3        開出順序       開出順序         47  ...         14         21        21
 4        大小順序       大小順序         04  ...         47         21        21
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配      獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎        普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號       任3個
 8      中獎  注數          0          0  ...       1837      20666     27647
 9      單注  獎金          0          0  ...       1000        400       400
 10   累至次  期獎金   64611434   64611434  ...        NaN        NaN       NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8         9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額      獎金總額
 1   110000043  110/04/27  110/04/27  ...   74350983   74350983  74350983
 2          獎號         獎號         獎號  ...         獎號        特別號       特別號
 3        開出順序       開出順序         20  ...         05         31        31
 4        大小順序       大小順序         05  ...         39         31        31
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配      獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎        普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號       任3個
 8      中獎  注數          0          0  ...       2252      22225     32285
 9      單注  獎金          0          0  ...       1000        400       400
 10   累至次  期獎金   42243648   42243648  ...        NaN        NaN       NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8         9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額      獎金總額
 1   110000042  110/04/23  110/04/23  ...   52956310   52956310  52956310
 2          獎號         獎號         獎號  ...         獎號        特別號       特別號
 3        開出順序       開出順序         37  ...         32         39        39
 4        大小順序       大小順序         18  ...         46         39        39
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配      獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎        普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號       任3個
 8      中獎  注數          0          0  ...       2072      21390     28623
 9      單注  獎金          0          0  ...       1000        400       400
 10   累至次  期獎金   21774011   21774011  ...        NaN        NaN       NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8          9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額       獎金總額
 1   110000041  110/04/20  110/04/20  ...  138231551  138231551  138231551
 2          獎號         獎號         獎號  ...         獎號        特別號        特別號
 3        開出順序       開出順序         05  ...         24         12         12
 4        大小順序       大小順序         05  ...         26         12         12
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配       獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎         普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號        任3個
 8      中獎  注數          1          1  ...       3993      33416      36455
 9      單注  獎金  100000000  100000000  ...       1000        400        351
 10   累至次  期獎金          0          0  ...        NaN        NaN        NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8          9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額       獎金總額
 1   110000040  110/04/16  110/04/16  ...  168432754  168432754  168432754
 2          獎號         獎號         獎號  ...         獎號        特別號        特別號
 3        開出順序       開出順序         21  ...         07         02         02
 4        大小順序       大小順序         07  ...         46         02         02
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配       獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎         普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號        任3個
 8      中獎  注數          1          1  ...       2635      26572      34244
 9      單注  獎金  127674004  127674004  ...       1000        400        400
 10   累至次  期獎金          0          0  ...        NaN        NaN        NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8          9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額       獎金總額
 1   110000039  110/04/13  110/04/13  ...  140784054  140784054  140784054
 2          獎號         獎號         獎號  ...         獎號        特別號        特別號
 3        開出順序       開出順序         35  ...         32         41         41
 4        大小順序       大小順序         11  ...         42         41         41
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配       獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎         普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號        任3個
 8      中獎  注數          0          0  ...       2035      21511      29050
 9      單注  獎金          0          0  ...       1000        400        400
 10   累至次  期獎金  106719098  106719098  ...        NaN        NaN        NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8          9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額       獎金總額
 1   110000038  110/04/09  110/04/09  ...  117091160  117091160  117091160
 2          獎號         獎號         獎號  ...         獎號        特別號        特別號
 3        開出順序       開出順序         18  ...         25         46         46
 4        大小順序       大小順序         06  ...         35         46         46
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配       獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎         普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號        任3個
 8      中獎  注數          0          0  ...       2311      21763      36211
 9      單注  獎金          0          0  ...       1000        400        400
 10   累至次  期獎金   81377080   81377080  ...        NaN        NaN        NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8         9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額      獎金總額
 1   110000037  110/04/06  110/04/06  ...   93349999   93349999  93349999
 2          獎號         獎號         獎號  ...         獎號        特別號       特別號
 3        開出順序       開出順序         22  ...         26         35        35
 4        大小順序       大小順序         01  ...         38         35        35
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配      獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎        普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號       任3個
 8      中獎  注數          0          0  ...       2102      22379     30000
 9      單注  獎金          0          0  ...       1000        400       400
 10   累至次  期獎金   62304563   62304563  ...        NaN        NaN       NaN

 [11 rows x 10 columns],
             0          1          2  ...          7          8         9
 0          期別        開獎日        開獎日  ...       獎金總額       獎金總額      獎金總額
 1   110000036  110/04/02  110/04/02  ...   75547749   75547749  75547749
 2          獎號         獎號         獎號  ...         獎號        特別號       特別號
 3        開出順序       開出順序         21  ...         17         26        26
 4        大小順序       大小順序         17  ...         42         26        26
 5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配      獎金分配
 6          項目         頭獎         頭獎  ...         陸獎         柒獎        普獎
 7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號       任3個
 8      中獎  注數          0          0  ...       1783      20246     25228
 9      單注  獎金          0          0  ...       1000        400       400
 10   累至次  期獎金   40948867   40948867  ...        NaN        NaN       NaN

 [11 rows x 10 columns]]

# Step 03

In [ ]:
df[1]

                                                   0
0  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000045  110/05/...
1  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000044  110/04/...
2  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000043  110/04/...
3  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000042  110/04/...
4  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000041  110/04/...
5  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000040  110/04/...
6  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000039  110/04/...
7  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000038  110/04/...
8  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000037  110/04/...
9  期別 開獎日 兌獎截止(註6)  銷售金額 獎金總額  110000036  110/04/...

In [ ]:
df[2]

            0          1          2  ...          7          8          9
0          期別        開獎日        開獎日  ...       獎金總額       獎金總額       獎金總額
1   110000045  110/05/04  110/05/04  ...  121406835  121406835  121406835
2          獎號         獎號         獎號  ...         獎號        特別號        特別號
3        開出順序       開出順序         27  ...         05         42         42
4        大小順序       大小順序         05  ...         37         42         42
5        獎金分配       獎金分配       獎金分配  ...       獎金分配       獎金分配       獎金分配
6          項目         頭獎         頭獎  ...         陸獎         柒獎         普獎
7     對中  獎號數         6個         6個  ...  任3個  ＋特別號  任2個  ＋特別號        任3個
8      中獎  注數          0          0  ...       2100      20583      34215
9      單注  獎金          0          0  ...       1000        400        400
10   累至次  期獎金   85311966   85311966  ...        NaN        NaN        NaN

[11 rows x 10 columns]